<?xml version="1.0" encoding="UTF-8"?>
<!-- ejemplodtd1-Miguel Amaya AH18059.xml -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		]>
<fichero>
 <ficha>
  <nombre sexo="Masculino" edad="22">Miguel Antonio</nombre>
  <apellido>Amaya Hernandez</apellido>
  <direccion>Zacatecoluica,La Paz</direccion>
 </ficha>
</fichero>
