<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="ejercicio-ii-1a-dtd.css"?>
<!-- ejercicio-ii-1a-dtd.xml-MN18015-->
<!DOCTYPE fichero [
    <!ELEMENT fichero (ficha+)>
    <!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
    <!ATTLIST nombre edad CDATA #IMPLIED>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT DUI (#PCDATA)>

    <!ELEMENT ficha_v2 (nombre, apellido, direccion*, DUI?, edad?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ATTLIST nombre genero (masculino|femenino) #REQUIRED>
    <!ATTLIST nombre edad CDATA #IMPLIED>
]>
<fichero>
    <ficha_v2>
        <nombre genero="masculino" edad="25">Juan</nombre>
        <apellido>Gomez</apellido>
        <direccion>Calle del Sol, 123</direccion>
        <DUI>123456789</DUI>
        <edad>25</edad>
    </ficha_v2>
</fichero>
