=== miguelxDd/Guia32-TPI115-Grupo05/Ejercicios/dtd_externa_juan/tareas.dtd
<!ELEMENT universidad (facultad, carrera, materia, grupo+)>
<!ATTLIST universidad atributoFijo CDATA #FIXED "ValorFijo">

<!ELEMENT facultad (nombre, codigo)>
<!ELEMENT carrera (nombre, codigo)>
<!ELEMENT materia (#PCDATA)>

<!ELEMENT grupo (formacion, numero, profesor, actividad*, integrante+)>
<!ATTLIST grupo tipoFormacion (GT|GL|GD) #REQUIRED>

<!ELEMENT formacion (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>

<!ELEMENT actividad (#PCDATA)>
<!ATTLIST actividad porcentaje CDATA #IMPLIED>

<!ELEMENT integrante (carne, nombres, apellidos, sexo)>
<!ATTLIST integrante atributoOpcional CDATA #IMPLIED>
<!ATTLIST integrante atributoRequerido CDATA #REQUIRED>

<!ELEMENT carne (#PCDATA)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ATTLIST sexo valorDefecto (M|F) "M">

=== miguelxDd/Guia32-TPI115-Grupo05/Ejercicios/dtd_externa_juan/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad SYSTEM "tareas.dtd">
<?xml-stylesheet type="text/css" href="tareas.css"?>
<universidad atributoFijo="UES">
  <facultad>
    <nombre>Ingenieria y Arquitectura</nombre>
    <codigo>(FAC123) - </codigo>
  </facultad>
  <carrera>
    <nombre>Ingenieria en Sistemas Informaticos</nombre>
    <codigo>(EISI115) - </codigo>
  </carrera>
  <materia>Teoria de Sistemas</materia>
  <grupo tipoFormacion="GT">
    <formacion>Te√≥rico</formacion>
    <numero>1</numero>
    <profesor>- Carlos Ernesto Garcia</profesor>
    <actividad porcentaje="10"> - La Parabola de la Rana</actividad>
    <integrante atributoOpcional="valorOpcional" atributoRequerido="valorRequerido">
      <carne>MN18015 - </carne>
      <nombres>Juan</nombres>
      <apellidos>Mendez - </apellidos>
      <sexo>M</sexo>
    </integrante>
     <integrante atributoOpcional="valorOpcional" atributoRequerido="valorRequerido">
      <carne>CE18014 - </carne>
      <nombres>Ada</nombres>
      <apellidos>Cabezas - </apellidos>
      <sexo>F</sexo>
    </integrante>
     <integrante atributoOpcional="valorOpcional" atributoRequerido="valorRequerido">
      <carne>CV20003 - </carne>
      <nombres>Jose</nombres>
      <apellidos>Chavez - </apellidos>
      <sexo>M</sexo>
    </integrante>
     <integrante atributoOpcional="valorOpcional" atributoRequerido="valorRequerido">
      <carne>AC170032 - </carne>
      <nombres>Esteban</nombres>
      <apellidos>Casco - </apellidos>
      <sexo>M</sexo>
    </integrante>
    <!-- ... otros integrantes ... -->
  </grupo>
  <!-- ... otros grupos ... -->
</universidad>
